SELECT 
  Q15POPULATION AS province,
  COUNT(*) AS total_youth,
  SUM(CASE WHEN Q19ATTE = 2 THEN 1 ELSE 0 END) AS unemployed_youth,
  ROUND(100.0 * SUM(CASE WHEN Q19ATTE = 2 THEN 1 ELSE 0 END) / COUNT(*), 1) AS youth_unemployment_rate
FROM lfs_q4_2020
WHERE Q13GENDER BETWEEN 1 AND 2
AND Q17EDUCATION BETWEEN 1 AND 8
GROUP BY Q15POPULATION
ORDER BY youth_unemployment_rate DESC;